insert into user_details(id, birth_date, name) values (10001,current_date(),'Amit')
insert into user_details(id, birth_date, name) values (10002,current_date(),'Neelam')
insert into user_details(id, birth_date, name) values (10003,current_date(),'Netra')
insert into user_details(id, birth_date, name) values (10004,current_date(),'Sharvi')
insert into post(id, description, user_id) values (20001,'I want to learn Microservices', 10001)
insert into post(id, description, user_id) values (20002,'I want to learn AWS', 10002)
insert into post(id, description, user_id) values (20003,'I want to learn Kubernetes', 10001)
insert into post(id, description, user_id) values (20004,'I want to learn Azure', 10003)